# Leveraging Data-Driven Insights to Uncover Value in the Indian Ecosystem


## Table of Contents
<!-- TOC -->

- [Step 1: Business Understanding](#step-1-business-understanding)
  - [Scenario](#scenario)
  - [Objective](#objective)
  - [Hypothesis: Influence of Top Investors](#hypothesis-influence-of-top-investors)
  - [Key Business Questions](#key-business-questions)
  - [Approach](#approach)
- [Step 2: Data Understanding](#step-2-data-understanding)
  - [Project Initialisation](#project-initialisation)
  - [Data Collection](#data-collection)
    - [Access the 2020 and 2021 data from Microsoft SQL Server](#access-the-2020-and-2021-data-from-microsoft-sql-server)
      - [Connect to the database using provided credentials](#connect-to-the-database-using-provided-credentials)
      - [Fetch Information Schema for tables in the database](#fetch-information-schema-for-tables-in-the-database)
      - [Load LP1\_startup\_funding2021 Data](#load-lp1_startup_funding2021-data)
      - [Load LP1\_startup\_funding2020 Data](#load-lp1_startup_funding2020-data)
    - [Access 2019 data from OneDrive](#access-2019-data-from-onedrive)
    - [Access the 2018 data from GitHub Repository](#access-the-2018-data-from-github-repository)
  - [Data Quality Considerations](#data-quality-considerations)
- [Step 3: Data Preparation](#step-3-data-preparation)
  - [Data Cleaning](#data-cleaning)
  - [Data Transformation](#data-transformation)
  - [Data Integration](#data-integration)

<!-- /TOC -->

[Back to Top](#Table-of-Contents)

## Step 1: Business Understanding

### Scenario
Your team is trying to venture into the Indian start-up ecosystem. As the data expert of the team, you are to investigate the ecosystem and propose the best course of action. 

### Objective
The primary objective is to analyse the funding landscape for start-ups in India from 2018 to 2021, focusing on identifying key trends and patterns. This analysis will provide crucial insights into the Indian start-up ecosystem, which will guide strategic decisions for entering and navigating the market effectively. 

### Hypothesis: Influence of Top Investors

**A. Rationale:**

Determining the influence of top investors on the success of start-ups can provide insights into the impact of investor reputation and networks. This can guide new start-ups in selecting potential investors and understanding the benefits of partnering with top-tier investors.

**B. Null Hypothesis (H0):**

Start-ups funded by top investors do not have higher subsequent funding rounds compared to those funded by less active investors.

**C. Alternative Hypothesis (H1):**

Start-ups funded by top investors have higher subsequent funding rounds compared to those funded by less active investors.

### Key Business Questions

**1. Is there a correlation between funding amounts from top investors (blue-chip investors) and the performance metrics of start-ups?**

Exploring the correlation between funding amounts from top investors and start-up performance metrics can help evaluate the effectiveness of investments made by these investors.

**2. Who are the most active investors in the Indian start-up ecosystem?**

Identifying the most active investors can help in analyzing the influence of top investors on subsequent funding rounds.

**3. Are there any geographical trends or hotspots for start-up funding in India?**

Analyzing geographical trends in start-up funding can provide context for understanding the influence of top investors in different regions.

**4. Are there any annual trends in start-up funding in India from 2018 to 2021?**

Understanding annual trends in start-up funding can provide background information for assessing the impact of top investors on subsequent funding rounds.

**5. Which sectors received the most funding each year?**

Analyzing the sectors that received the most funding can provide additional context for evaluating the influence of top investors.

**6. What impact do the years of existence or age of a start-up have on investment opportunities?**

Understanding how the age of a start-up influences investment opportunities can provide insights into whether start-ups funded by top investors indeed have higher subsequent funding rounds.

**7. What are the funding stages (seed, series A, etc.) that received the highest investments?**

Examining the funding stages that received the highest investments can offer insights into the funding patterns of top investors.

### Approach
In conclusion, to understand the trends and patterns in start-up funding in India from 2018 to 2021, a comprehensive approach will be implemented. This will involve gathering detailed data on start-ups, funding amounts, stages, sectors, geographic locations, and investors. The collected data will be analyzed using descriptive statistics, trend analysis, visualizations, and statistical tests to derive key insights. These insights will be compiled into detailed reports and dashboards, providing actionable information and strategic recommendations. Ultimately, this analysis will offer data-driven guidance on the most promising sectors, regions, and funding stages to focus on, identify key investors for potential partnerships, and assess the overall attractiveness of the Indian start-up market for strategic entry.

[Back to Top](#Table-of-Contents)

## Step 2: Data Understanding

`Data Collection`

To effectively analyse the Indian start-up ecosystem from 2018 to 2021, comprehensive data collection is crucial. The data will be sourced from multiple datasets that detail startup funding activities within this period. Each dataset will encompass various aspects essential for a holistic understanding of the funding landscape. Specifically, the datasets will include:

**A. Start-up Details:**

-   Company/Brand: Name of the company/start-up

-   Founded: Year start-up was founded

-   Headquarters/Location: The geographical location of the start-up, including city and region.

-   Sector/Industry: The industry or sector in which the start-up operates, such as healthtech, fintech, etc.

-   What it does/About Company: Description about Company

-   Founders: Founders of the Company

**B. Funding Information:**

-   Amount: The total amount of funding received by the start-up in each funding round.

-   Stage/Round: Details of the funding stages such as seed, series A, series B, etc.

**C. Investors' Information:**

-   Investors: The names of the investors or investment firms involved.

`Data Quality Considerations`

Ensuring high data quality is paramount for reliable analysis and actionable insights. Key considerations for maintaining data quality include:

**A. Completeness:**

Ensure that all necessary fields are filled in across the datasets. This includes making sure that no critical information is missing for any of the start-ups, funding rounds, or investors.

**B. Consistency:**

Handle any inconsistencies in data entries. This may involve standardizing entries for sectors, locations, and investor names to ensure uniformity. For example, variations in how sectors are labeled (e.g., "Healthtech" vs. "Health Technology") should be standardized to a single format.

**D. Handling Missing Data:**

Identify and address missing data points. Techniques such as imputation, where appropriate, or excluding certain records if the missing data is minimal and does not impact overall analysis, will be employed.

### Project Initialisation

In [48]:
# Importing necessary libraries
from dotenv import dotenv_values
import pyodbc
import requests
import pandas as pd
import numpy as np
import calendar
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# Suppressing all warnings to avoid cluttering the output
warnings.filterwarnings("ignore")

# Set display options for Pandas DataFrame
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", 100)

### Data Collection

The task involves accessing three different datasets from different sources: a database, OneDrive, and a GitHub repository. Each dataset has a specific method of access, such as querying a database using ODBC or ORM library, downloading a file programmatically using the requests library from OneDrive, and cloning or downloading a file from a GitHub repository using gitpython or requests library.

#### Access the 2020 and 2021 data from Microsoft SQL Server

##### Connect to the database using provided credentials

In [30]:
# Load environment variables from .env file
environment_variables = dotenv_values("LP1_DAP.env")

# Retrieve environment variables for database connection
server_name = environment_variables.get("server")
password = environment_variables.get("password")
login = environment_variables.get("login")
database_name = environment_variables.get("database")

# Create a database connection string using pyodbc
connection_string = f"DRIVER={{SQL Server}};SERVER={server_name};DATABASE={database_name};UID={login};PWD={password};"

#Establish a connection to the database
try:
    connection = pyodbc.connect(connection_string)
    print("Connection successful:", connection_string)    
except Exception as e:
    print("Connection failed:", e)

Connection successful: DRIVER={SQL Server};SERVER=dap-projects-database.database.windows.net;DATABASE=dapDB;UID=LP1_learner;PWD=Hyp0th3s!$T3$t!ng;

##### Fetch Information Schema for tables in the database

In [31]:
# Define the SQL query to show specific tables in the database
db_query = """
        SELECT *
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'dbo'
        """
# Read data from the SQL query result into a DataFrame using the established database connection
schema_df = pd.read_sql(query, connection)

#  Check whether data has been retrieved successfully to confirm successful connection to database
try:
    scheschema_df = pd.read_sql(db_query, connection)
    print("Data retrieved successfully")
    print(schema_df)
except Exception as e:
    print("Failed to retrieve data:", e)

Data retrieved successfully
  TABLE_CATALOG TABLE_SCHEMA               TABLE_NAME  TABLE_TYPE
0         dapDB          dbo  LP1_startup_funding2021  BASE TABLE
1         dapDB          dbo  LP1_startup_funding2020  BASE TABLE

##### Load LP1_startup_funding2021 Data

In [32]:
# Define the SQL query to show specific tables in the database
db_query1 = """
        SELECT *
        FROM LP1_startup_funding2021        
        """
# Read data from the SQL query result into a DataFrame using the established database connection
df2021 = pd.read_sql(db_query1, connection)

# Display DataFrame Info
df2021.info()
print()

# Display the DataFrame
df2021.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1209 entries, 0 to 1208
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company_Brand  1209 non-null   object
 1   Founded        1208 non-null   float64
 2   HeadQuarter    1208 non-null   object
 3   Sector         1209 non-null   object
 4   What_it_does   1209 non-null   object
 5   Founders       1205 non-null   object
 6   Investor       1147 non-null   object
 7   Amount         1206 non-null   object
 8   Stage          781 non-null    object
dtypes: float64(1), object(8)
memory usage: 85.1+ KB

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage
0,Unbox Robotics,2019.0,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First","$1,200,000",Pre-series A
1,upGrad,2015.0,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management","$120,000,000",None
2,Lead School,2012.0,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital","$30,000,000",Series D
3,Bizongo,2015.0,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital","$51,000,000",Series C
4,FypMoney,2021.0,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal","$2,000,000",Seed

##### Load LP1_startup_funding2020 Data

In [33]:
# Define the SQL query to show specific tables in the database
db_query2 = """
        SELECT *
        FROM LP1_startup_funding2020        
        """
# Read data from the SQL query result into a DataFrame using the established database connection
df2020 = pd.read_sql(db_query2, connection)

# Display DataFrame Info
df2020.info()
print()

# Display the DataFrame
df2020.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company_Brand  1055 non-null   object
 1   Founded        842 non-null    float64
 2   HeadQuarter    961 non-null    object
 3   Sector         1042 non-null   object
 4   What_it_does   1055 non-null   object
 5   Founders       1043 non-null   object
 6   Investor       1017 non-null   object
 7   Amount         801 non-null    float64
 8   Stage          591 non-null    object
 9   column10       2 non-null      object
dtypes: float64(2), object(8)
memory usage: 82.5+ KB

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10
0,Aqgromalin,2019.0,Chennai,AgriTech,Cultivating Ideas for Profit,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,None,None
1,Krayonnz,2019.0,Bangalore,EdTech,An academy-guardian-scholar centric ecosystem ...,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed,None
2,PadCare Labs,2018.0,Pune,Hygiene management,Converting bio-hazardous waste to harmless waste,Ajinkya Dhariya,Venture Center,NaN,Pre-seed,None
3,NCOME,2020.0,New Delhi,Escrow,Escrow-as-a-service platform,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,None,None
4,Gramophone,2016.0,Indore,AgriTech,Gramophone is an AgTech platform enabling acce...,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,None,None

#### Access 2019 data from OneDrive

In [27]:
# Path of CSV file
file_path = r"C:\Users\Nfayem\OneDrive\Azubi_Africa\GitHub\LP1_Data_Analytics_Project\Data\startup_funding2019.csv"

# Read the CSV file into a pandas DataFrame
df2019 = pd.read_csv(file_path)

# Display DataFrame Info
df2019.info()
print()

# Display the DataFrame
df2019.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company/Brand  89 non-null     object
 1   Founded        60 non-null     float64
 2   HeadQuarter    70 non-null     object
 3   Sector         84 non-null     object
 4   What it does   89 non-null     object
 5   Founders       86 non-null     object
 6   Investor       89 non-null     object
 7   Amount($)      89 non-null     object
 8   Stage          43 non-null     object
dtypes: float64(1), object(8)
memory usage: 6.4+ KB

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
0,Bombay Shaving,NaN,NaN,Ecommerce,Provides a range of male grooming products,Shantanu Deshpande,Sixth Sense Ventures,"$6,300,000",NaN
1,Ruangguru,2014.0,Mumbai,Edtech,A learning platform that provides topic-based ...,"Adamas Belva Syah Devara, Iman Usman.",General Atlantic,"$150,000,000",Series C
2,Eduisfun,NaN,Mumbai,Edtech,It aims to make learning fun via games.,Jatin Solanki,"Deepak Parekh, Amitabh Bachchan, Piyush Pandey","$28,000,000",Fresh funding
3,HomeLane,2014.0,Chennai,Interior design,Provides interior designing solutions,"Srikanth Iyer, Rama Harinath","Evolvence India Fund (EIF), Pidilite Group, FJ...","$30,000,000",Series D
4,Nu Genes,2004.0,Telangana,AgriTech,"It is a seed company engaged in production, pr...",Narayana Reddy Punyala,Innovation in Food and Agriculture (IFA),"$6,000,000",NaN

#### Access the 2018 data from GitHub Repository

In [52]:
# URL of the file to download
url = "https://github.com/Azubi-Africa/Career_Accelerator_LP1-Data_Analysis/raw/main/startup_funding2018.csv"

# Local file path where the file will be saved
local_file_path = r"C:\Users\Nfayem\OneDrive\Azubi_Africa\GitHub\LP1_Data_Analytics_Project\Data\startup_funding2018.csv"

# Send a GET request to the URL
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Write the content of the response to the specified file path
    with open(local_file_path, "wb") as f:
        f.write(response.content)
    print("File downloaded successfully")
else:
    print("Failed to download file")

# Read the downloaded CSV file into a DataFrame
df2018 = pd.read_csv(local_file_path)

# Display DataFrame Info
print()
df2018.info()
print()

# Display the DataFrame
df2018.head()

File downloaded successfully

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company Name   526 non-null    object
 1   Industry       526 non-null    object
 2   Round/Series   526 non-null    object
 3   Amount         526 non-null    object
 4   Location       526 non-null    object
 5   About Company  526 non-null    object
dtypes: object(6)
memory usage: 24.8+ KB

,Company Name,Industry,Round/Series,Amount,Location,About Company
0,TheCollegeFever,"Brand Marketing, Event Promotion, Marketing, S...",Seed,250000,"Bangalore, Karnataka, India","TheCollegeFever is a hub for fun, fiesta and f..."
1,Happy Cow Dairy,"Agriculture, Farming",Seed,"₹40,000,000","Mumbai, Maharashtra, India",A startup which aggregates milk from dairy far...
2,MyLoanCare,"Credit, Financial Services, Lending, Marketplace",Series A,"₹65,000,000","Gurgaon, Haryana, India",Leading Online Loans Marketplace in India
3,PayMe India,"Financial Services, FinTech",Angel,2000000,"Noida, Uttar Pradesh, India",PayMe India is an innovative FinTech organizat...
4,Eunimart,"E-Commerce Platforms, Retail, SaaS",Seed,—,"Hyderabad, Andhra Pradesh, India",Eunimart is a one stop solution for merchants ...

### Data Quality Considerations
The datasets are carefully examined to identify common data quality issues such as missing values, outliers, duplicates, inconsistencies, and errors.

[Back to Top](#Table-of-Contents)

## Step 3: Data Preparation

### Data Cleaning
Effective data cleaning is crucial to ensure the integrity and usability of the dataset for analysis. The steps involved in data cleaning will include:

**A. Remove Duplicates:**

Identify and remove duplicate records to ensure that each entry is unique and not counted multiple times. This involves checking for repeated start-up names, funding amounts, and investor details.

**B. Eliminate Irrelevant Data:**

Remove any data that is not relevant to the analysis. This could include fields that do not contribute to the understanding of funding trends or extraneous information not related to start-up funding.

**C. Handle Missing Values:**

- Imputation: For fields with missing data, use appropriate imputation methods to fill in the gaps. This could involve using mean, median, or mode for numerical values, or the most frequent category for categorical variables.

- Removal: If the amount of missing data is substantial and imputation is not feasible, records are removed entirely. However, this is done if deletion does not significantly impact the overall dataset integrity.
  
**D. Standardize Formats:**

- Dates: Ensure all date fields follow a consistent format (e.g., YYYY-MM-DD) to facilitate accurate time-based analysis.
  
- Funding Amounts: Standardize funding amounts to a common currency and format, ensuring consistency in how values are presented and analysed.

- Categorical Variables: Ensure uniform labelling for categorical variables such as sectors, funding stages, and locations to avoid discrepancies (e.g., "Health Care" vs. "Healthcare").

### Data Transformation
Data transformation involves modifying the data to better suit the analytical methods to be applied. The steps include:

**A. Aggregate Funding Data:**

- By Year: Summarize funding data on an annual basis to identify year-over-year trends in funding amounts and number of funding rounds.
  
- By Sector: Aggregate funding by sector to determine which industries are receiving the most investment.
  
- By Funding Stage: Summarize data by funding stage (e.g., seed, series A, series B) to understand the distribution of investments across different start-up maturity levels.
  
**B. Normalize Funding Amounts:**

Adjust funding amounts for inflation or currency changes over the years to ensure that comparisons are made on a like-for-like basis. This is important for accurately assessing trends and changes in funding amounts over time.

### Data Integration
Data integration involves combining multiple datasets into a single, comprehensive dataset for analysis. This includes:

**A. Combine Datasets from Different Years:**

Merge datasets from 2018 to 2021 into a unified dataset. Ensure that the structure and format of data from each year are consistent to facilitate seamless integration. Address any discrepancies or differences in data schema across years to create a cohesive dataset.

**B. Ensure Consistency:**

Verify that all integrated data follows the standardized formats and labelling conventions established during the data cleaning process. Cross-reference and validate combined data to ensure no information is lost or misrepresented during the integration process.

[Back to Top](#Table-of-Contents)